### ISSUE TITLE
Incompatible with rollup-plugin-babel >2.5.0

### ISSUE THREAD

**Issue by madeleineostoja** [bedeoverend/rollup-plugin-file#2]
As of 2.5.0 `rollup-plugin-babel` explicitly expects a path, not a vinyl. This breaks this plugin.

**Comment by bedeoverend** [comment]
Depends on what you inject into rollup. So it's somewhat fundamental to rollup and the existence of this plugin. Even changing how this plugin works won't fix the issue, you'll need to pass a vinyl that can imitate a string to get around it. [gulp-rollup-file](https://github.com/bedeoverend/gulp-rollup-file) which injects a vinyl has been patched in that one to imitate a string in [this patch](https://github.com/bedeoverend/gulp-rollup-file/commit/c531efd8336b145e25f8d0a2b3267fdec51116ae)
